# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'HampKit' do
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Alamofire', '~> 4.4'

  target 'HampKitTests' do
      pod 'Firebase/Auth'
      pod 'Firebase/Database'
      pod 'Firebase/Core'
      pod 'Firebase/Messaging'
  end

end
