# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'HampKit' do
    pod 'FirebaseCommunity', :git => 'https://github.com/ulidev/firebase-ios-sdk.git'
    pod 'FirebaseCommunity/Auth', :git => 'https://github.com/ulidev/firebase-ios-sdk.git'
    pod 'FirebaseCommunity/Database', :git => 'https://github.com/ulidev/firebase-ios-sdk.git'
    pod 'Alamofire', '~> 4.4'

  target 'HampKitTests' do
      pod 'FirebaseCommunity', :git => 'https://github.com/ulidev/firebase-ios-sdk.git'
      pod 'FirebaseCommunity/Auth', :git => 'https://github.com/ulidev/firebase-ios-sdk.git'
      pod 'FirebaseCommunity/Database', :git => 'https://github.com/ulidev/firebase-ios-sdk.git'
  end

end
